### ISSUE TITLE
Implement handlers for all the defined routes

### ISSUE THREAD

**Issue by InternationalKoder** [ami-lab/CONSERT-Middleware#11]
### Why

The agents are implemented as Vert.x servers, so the communications between them are made with routes. We need to implement these routes to make the agents able to communicate.

### What

Implement the following routes:

- [x] PUT /tasking_command/
- [x] GET /context_assertions/
- [x] GET /context_assertions/:id/
- [x] PUT /context_assertions/:id/
- [x] DELETE /context_assertions/:id/
- [x] POST /assertion_capability_subscriptions/
- [x] GET /assertion_capability_subscriptions/:id/
- [x] PUT /assertion_capability_subscriptions/:id/
- [x] DELETE /assertion_capability_subscriptions/:id/
- [x] POST /insert_context_assertion/
- [x] POST /insert_entity_descriptions/
- [x] POST /update_entity_descriptions/
- [ ] POST /activate_context_assertion/
- [x] GET /context_query/
- [x] POST /context_subscriptions/
- [x] GET /context_subscriptions/:id/
- [x] PUT /context_subscriptions/:id/
- [x] DELETE /context_subscriptions/:id/

**Comment by asorici** [comment]
Considering resolved.
Opening follow-up for remaining routes.
Closing, thank you!
