### ISSUE TITLE
Include Vert.x configuration in deployment ontology

### ISSUE THREAD

**Issue by InternationalKoder** [ami-lab/CONSERT-Middleware#32]
### Why

Since we changed the implementation of the agents, their configuration has also changed. We want to alter the deployment ontology so that it models the new configuration.

### What

 - [ ] Include Vert.x platform configuration options instead of JADE specific ones in CONSERT Deployment Ontology.
 - [ ] Create sample deployment configuration for HLATest scenario starting from the one for the SmartClassroom example

**Comment by asorici** [comment]
What is really needed initially is just a creation of the corresponding RDFBeans parser that can retrieve the AgentAddress configuration for the CtxSensor, CtxCoord and CtxQueryHandler agents involved in the HLATest scenario.

Start out from the existing implementation of the PlatformSpecification, AgentSpecification and AgentAddress classes and add the minimally required annotations to make the parsing work.
