### ISSUE TITLE
Investigate options for RDF to Java beans conversion

### ISSUE THREAD

**Issue by InternationalKoder** [ami-lab/CONSERT-Middleware#5]
### Why
We need this for converting between RDF payload of the CONSERT Middleware agent communication protocols and backend Java classes handled by the Vert.x based implementation.

### What
 - document listing options and their advnatages/disadvantages

**Comment by InternationalKoder** [comment]
- Eclipse RDF4J: http://rdf4j.org/
	-> very good documentation with examples + javadoc
	-> easy to use
	-> heavy: many libraries probably that are probably useless for what we want to do
	-> maintained (last version: June 8, 2017)
	-> supports all mainstream RDF file formats, including RDF/XML, Turtle, N-Triples,  N-Quads, JSON-LD, TriG and TriX
	-> successor of Sesame

- jenabean: https://code.google.com/archive/p/jenabean/
	-> based on annotation, nothing to change in the code
	-> easy to use (only a few lines for conversion RDF <--> Java bean class)
	-> wiki to learn to use it
	-> lightweight
	-> not maintained


- **RDFBeans: http://rdfbeans.sourceforge.net/**
	-> based on RDF2Go -> dependency
	-> many examples + javadoc
	-> easy to use
	-> based on annotation, nothing to change in the code
	-> many annotations to add




- Apache Jena: http://jena.apache.org/index.html
	-> seems complicated to use for this type of conversion

- Xmappr: https://code.google.com/archive/p/xmappr/
	-> for XML, not specific to RDF

- RDF2Go: http://semanticweb.org/wiki/RDF2Go
	-> example: https://github.com/semweb4j/semweb4j/blob/master/org.semweb4j.rdf2go.impl.jena/src/main/examples/org/ontoware/rdf2go/example/ToN3.java
	-> easy to use
	-> documentation difficult to find?

- Pinto (or Empire): https://github.com/stardog-union/pinto
	-> nothing to change in the code, no annotation needed
	-> easy to use
	-> can't be imported as a Maven dependency

- So(m)mer: https://github.com/bblfish/sommer
	-> no documentation, just an example
	-> easy to use
	-> old and not maintained

Bolded entry is the preferred candidate.

**Comment by asorici** [comment]
We have opted for RDFBeans and the RDF4J in memory repository.
Closing issue, thank you!
